# Loading R packages
```{r}
library(dplyr)
library(lubridate)
library(stringr)
library(zoo)
library(magrittr)
library(tidyr)
```

## Load the data
```{r}
load("data/df_FF_full.Rdata")

df_FF_full %<>%
  spread(key = var, value = value)
```

## Cleaning the data 
```{r}
df_FF_clean = df_FF_full %>%
  mutate(event = tolower(event),
         geo = NA,
         geo = ifelse(currency == "AUD", "Australia", geo),
         geo = ifelse(currency == "USD", "USA", geo),
         geo = ifelse(currency == "CHF", "Switzerland", geo),
         geo = ifelse(currency == "GBP", "UK", geo),
         geo = ifelse(currency == "EUR", "Euro Area", geo),
         geo = ifelse(currency == "CAD", "Canada", geo),
         geo = ifelse(currency == "NZD", "New Zealand", geo),
         geo = ifelse(currency == "CNY", "China", geo),
         geo = ifelse(grepl("french", event), "France", geo),
         geo = ifelse(grepl("italian", event), "Italy", geo),
         geo = ifelse(grepl("spanish", event), "Spain", geo),
         geo = ifelse(grepl("german", event), "Germany", geo),
         event = str_remove(event, "french "),
         event = str_remove(event, "italian "),
         event = str_remove(event, "german "),
         event = str_remove(event, "spanish ")) %>%
  filter(!is.na(geo)) %>%
  select(date, geo, currency, event, event_id, forecast, observation, previous_obs, impact, release_time, Description, `FF Notes`, `FF Notice`, Frequency, Measures)

# cleaning numbers
df_FF_clean %<>%
  gather(-date, -geo, -currency, -event, -event_id, -impact, -release_time,
         -Description, -`FF Notes`, -`FF Notice`, -Frequency, -Measures,
         key = var, value = value) %>%
  mutate(value = str_remove(value, "%"),
         value = str_replace(value, "K", "000"),
         value = str_replace(value, "M", "000000"),
         value = str_replace(value, "B", "000000000"),
         value = str_remove(value, "<"),
         value = as.numeric(value)) %>%
  spread(key = var, value = value) %>%
  relocate(date, release_time, geo, currency)

# keeping only data event (excluding speeches and meetings for instance)
df_FF_clean %<>%
  filter(!is.na(observation))

# finding problematic events (duplicates) and dropping them to keep only single events (for now)
df_FF_clean %<>%
  mutate(index = 1:nrow(df_FF_clean)) %>%
  group_by(date,geo,event) %>%
  mutate(id_drop = ifelse(n()>1 & index == max(index), 1, 0)) %>%
  # filter(n()>1) %>%
  ungroup() %>%
  filter(id_drop == 0) %>%
  select(-id_drop,-index)

# creating forecast error variable
df_FF_clean %<>%
  mutate(error = forecast - observation)

# creating change variable
df_FF_clean %<>%
  mutate(change = observation - previous_obs)

save(df_FF_clean, file = "data/df_FF_clean.Rdata")
```

## Finding the target period
```{r}
library(readr)

df_FF_clean %<>%
  mutate(Frequency = tolower(Frequency),
         freq = NA,
         freq = ifelse(grepl("monthly", Frequency), "monthly", freq),
         freq = ifelse(grepl("weekly", Frequency), "weekly", freq),
         freq = ifelse(grepl("quarterly", Frequency), "quarterly", freq),
         freq = ifelse(grepl("every 3 months", Frequency), "quarterly", freq))

# lag
df_FF_clean %<>%
  mutate(target = as.Date(NA),
         lag = parse_number(Frequency),
         target = ifelse(!grepl("days", Frequency) &
                          grepl("current", Frequency) &
                          freq == "quarterly", as.character(as.yearqtr(date)), target),
         target = ifelse(!grepl("days", Frequency) &
                          (grepl("after", Frequency) | grepl("following", Frequency)) &
                          freq == "quarterly", as.character(as.yearqtr(date)-1/4), target),
         target = ifelse(!grepl("days", Frequency) &
                          grepl("current", Frequency) &
                          freq == "monthly", as.character(as.yearmon(date)), target),
         target = ifelse(!grepl("days", Frequency) &
                          (grepl("after", Frequency) | grepl("following", Frequency)) &
                          freq == "monthly", as.character(as.yearmon(date)-1/12), target),
         target = ifelse(!grepl("days", Frequency) &
                          (grepl("after", Frequency)) &
                          freq == "weekly", as.character(week(date)-1), target),
         #current
         target = ifelse((grepl("current", Frequency) | grepl("into", Frequency)) &
                          freq == "monthly", as.character(as.yearmon(date)), target),
         target = ifelse((grepl("current", Frequency) | grepl("into", Frequency) | grepl("before", Frequency)) & freq == "quarterly", as.character(as.yearqtr(date)), target),
         #monthly
         target = ifelse((grepl("after", Frequency) | grepl("following", Frequency)) &
                          freq == "monthly" & !is.na(lag) & lag <= 90,
                         as.character(as.yearmon(date)-3/12), target),
         target = ifelse((grepl("after", Frequency) | grepl("following", Frequency)) &
                          freq == "monthly" & !is.na(lag) & lag <= 60,
                         as.character(as.yearmon(date)-2/12), target),
         target = ifelse((grepl("after", Frequency) | grepl("following", Frequency)) &
                          freq == "monthly" & !is.na(lag) & lag <= 30,
                         as.character(as.yearmon(date)-1/12), target),
         #quarterly
         target = ifelse((grepl("after", Frequency) | grepl("following", Frequency)) &
                          freq == "quarterly" & !is.na(lag) & lag <= 180,
                         as.character(as.yearqtr(date)-2/4), target),
         target = ifelse((grepl("after", Frequency) | grepl("following", Frequency)) &
                          freq == "quarterly" & !is.na(lag) & lag <= 90,
                         as.character(as.yearqtr(date)-1/4), target)) %>%
  select(-lag)

df_FF_clean %>%
  select(Frequency, event, target, freq, geo) %>%
  group_by(Frequency, event) %>%
  distinct() %>%
  filter(is.na(target))
# filter(!grepl("days", Frequency) &
#                           (grepl("after", Frequency)) &
#                           freq == "weekly")

save(df_FF_clean, file = "data/df_FF_clean.Rdata")
```

## adding inflation and employment indicator
```{r}
library(sjmisc)

infl = c("price", "infl", "cpe", "cpi", "pce", "ppi", "pi", "hpi",
         "wage", "earnings", "earning", "wpi", "inflation", "labor cost")

empl = c("employment", "unemployment", "claim", "claimant")

econ_g = c("gdp", "ip", "manufacturing", "construction", "vehicle sales",
           "services", "orders", "retail sales", "economic expectations",
           "leading index", "wholesale sales", "cbi", "industrial new orders",
           "credit card spending", "pmi")

housing = c("mortgage", "home", "building", "housing", "house")

confidence = c("confidence", "home", "sentiment", "climate")

monetary_pol = c("rate")

df_FF_clean %<>%
  group_by(event) %>%
  mutate(type = NA,
         type = ifelse(any(str_contains(event, infl)), "inflation", type),
         type = ifelse(any(str_contains(event, empl)), "employment", type),
         type = ifelse(any(str_contains(event, econ_g)), "economic growth", type),
         type = ifelse(any(str_contains(event, housing)), "housing", type),
         type = ifelse(any(str_contains(event, confidence)), "confidence", type),
         type = ifelse(any(str_contains(event, monetary_pol)), "monetary_pol", type)) %>%
  ungroup()

save(df_FF_clean, file = "data/df_FF_clean.Rdata")
```

## sort by release_time
```{r}
df_FF_clean %<>%
  arrange(release_time)

save(df_FF_clean, file = "data/df_FF_clean.Rdata")
```

