```{r}
rD <- RSelenium::rsDriver(browser = "firefox")
remDr <- rD[["client"]]
remDr$open()
remDr$navigate("https://www.forexfactory.com/calendar?day=feb2.2022")
# remDr$navigate("https://www.forexfactory.com/#detail=133859")
Sys.sleep(5)
webElem <- remDr$findElement(using = "css selector", "[data-eventid='124055']")
webElem <- webElem$findElement(using = "class", ".detail")
webElem$highlightElement()
webElem$clickElement()
webElem$getElementText()
# webElem$executeScript('arguments[0].click();')
```

```{r, eval = FALSE}
## https://stackoverflow.com/questions/74811360/how-to-install-chromedriver-with-binman-package-on-mac
# https://stackoverflow.com/questions/60362018/macos-catalinav-10-15-3-error-chromedriver-cannot-be-opened-because-the-de
# https://stackoverflow.com/questions/68289474/selenium-headless-how-to-bypass-cloudflare-detection-using-selenium
binman::list_versions(appname = "chromedriver")
binman::app_dir("chromedriver")

eCaps <- list(chromeOptions = list(
  args = c('--headless')
))

require(RSelenium)
remDr <- rsDriver(browser = "chrome",
                  extraCapabilities = eCaps,
                  port = 4000L)
remDr = remDr[["client"]]
remDr$open()
Sys.sleep(5)
remDr$navigate("https://www.forexfactory.com/")
Sys.sleep(5)
webElem <- remDr$findElement(using = "css selector", ".detail")
webElem$highlightElement()
webElem$clickElement()
```
