---
title: "Graphs"
output: html_document
date: "2023-02-02"
---

# Loading R packages
```{r}
library(dplyr)
library(magrittr)
library(zoo)
library(tidyr)
library(ggplot2)
```

```{r}
load("data/df_FF_clean.Rdata")
```

# inflation
```{r}
## forecast
df = df_FF_clean %>%
  filter(type == "inflation",
         !grepl("brc", event),
         !grepl("rightmove", event),
         !grepl("reinz", event),
         freq == "monthly",
         geo %in% c("Euro Area", "Canada", "USA", "UK", "Australia", "New Zealand")) %>%
  mutate(target = as.yearmon(target)) %>%
  arrange(geo, target)

ggplot(data = df,
       aes(x = target,
           y = forecast,
           colour = geo)) +
  ggtitle("forecast") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)

## error
ggplot(data = df,
       aes(x = target,
           y = error,
           colour = geo)) +
  ggtitle("error") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)
```

# employment
```{r}
## forecast
df = df_FF_clean %>%
  filter(type == "employment",
         # grepl("cpi", event),
         freq == "monthly",
         geo %in% c("Euro Area", "Canada", "USA", "UK", "Australia", "New Zealand")) %>%
  mutate(target = as.yearmon(target)) %>%
  arrange(geo, target)


ggplot(data = df,
       aes(x = target,
           y = forecast,
           colour = geo)) +
  ggtitle("forecast") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)

## error
ggplot(data = df,
       aes(x = target,
           y = error,
           colour = geo)) +
  ggtitle("error") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)
```

# gdp
```{r}
## forecast
df = df_FF_clean %>%
  filter(grepl("gdp", event),
         freq == "quarterly",
         geo %in% c("Euro Area", "Canada", "USA", "UK", "Australia", "New Zealand")) %>%
  mutate(target = as.yearqtr(target)) %>%
  arrange(geo, target)

ggplot(data = df,
       aes(x = target,
           y = forecast,
           colour = geo)) +
  ggtitle("forecast") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)

## error
ggplot(data = df,
       aes(x = target,
           y = error,
           colour = geo)) +
  ggtitle("error") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)
```

# gdp
```{r}
### forecast
df = df_FF_clean %>%
  filter(grepl("consumer", event),
         freq == "monthly") %>%
  mutate(target = as.yearmon(target)) %>%
  arrange(geo, target)

ggplot(data = df,
       aes(x = target,
           y = forecast,
           colour = geo)) +
  ggtitle("forecast") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)

### error
df = df_FF_clean %>%
  filter(grepl("consumer", event),
         freq == "monthly") %>%
  mutate(target = as.yearmon(target)) %>%
  arrange(geo, target)

ggplot(data = df,
       aes(x = target,
           y = error,
           colour = geo)) +
  ggtitle("error") +
  geom_point(alpha = 0.5) +
  facet_wrap(~ event, scales = "free_y", ncol = 3) +
  scale_x_yearmon(format = "%y", n = 10)
```