---
title: "Rd3f"
format: gfm
---

R code for creating a dataframe out of the [Forex Factory](https://www.forexfactory.com) online economic calendar.

* `build_df()` creates or update a dataframe out of Forex Factory HTML source pages.
* `clean_df()` cleans and categorises the data.

```{r, message = FALSE}
source("forex.R")
```

```{r, warning = FALSE}
# load the raw dataset generated previously (optional)
df = read_parquet("data/df_ff_raw.parquet")

# set the dates to scrap from forex factory 
date_start = "2024-04-07"
date_end = "2024-04-11"

# update the dataset
df_updated = build_df(date_start, date_end, df) # can be left empty if a new dataframe should be created

# clean the dataset
df_clean = clean_df(df_updated)
```

#### Snapshot of the dataframe
```{r}
library(dplyr)
library(knitr)

df_day = df_clean %>%
  filter(date == "2024-04-11")

kable(df_day, format = "html")
```

* Note that these data are protected by the [copyright](https://www.forexfactory.com/notices#copyrightof) of Fair Economy, Inc.