---
title: "Summary"
output: html_document
date: "2023-02-02"
---

# Loading R packages
```{r}
library(dplyr)
library(magrittr)
library(zoo)
library(tidyr)
library(kableExtra)
```

## 
```{r}
load("data/df_FF_clean.Rdata")

df_sum = df_FF_clean %>%
  select(geo, event, date, forecast, type, freq) %>%
  filter(!is.na(forecast)) %>%
  group_by(geo, event) %>%
  summarise(forecasts_available_from = as.yearmon(min(date)),
            forecasts_available_to = as.yearmon(max(date)),
            nb_forecasts = length(!is.na(forecast)),
            type = unique(type),
            freq = unique(freq))
  
df_sum %>%
  group_by(geo) %>%
  summarise(nb_event = length(unique(event))) %>%
  arrange(-nb_event) %>%
  kbl(caption = "Number of variables") %>%
  kable_classic(full_width = F, html_font = "Cambria")

df_sum %>%
  filter(type == "inflation") %>%
  kbl(caption = "Price expectation data") %>%
  kable_classic(full_width = F, html_font = "Cambria")

df_sum %>%
  filter(type == "economic growth") %>%
  kbl(caption = "Employment expectation data") %>%
  kable_classic(full_width = F, html_font = "Cambria")

df_sum %>%
  filter(type == "employment") %>%
  kbl(caption = "Employment expectation data") %>%
  kable_classic(full_width = F, html_font = "Cambria")

df_sum %>%
  filter(event %in% c("overnight rate", "official bank rate", "main refinancing rate",
                      "official cash rate", "federal funds rate", "snb policy rate")) %>%
  kbl(caption = "Employment expectation data") %>%
  kable_classic(full_width = F, html_font = "Cambria")

  # mutate(from = as.character(forecasts_available_from),
  #        to = as.character(forecasts_available_to)) %>%
  # select(-type, -forecasts_available_from, -forecasts_available_to) %>%
  # stargazer(summary = FALSE, rownames=FALSE)
```

